webhookURL: "https://discordapp.com/api/webhooks/874614146539352064/YpEE9pF44bmIxIzngZ60dFD6waPZtjn0IExO1nT4vLbp0kX-oIoNfbjpLgieJLlDPap2"
discordToken: "ODYyMzIwMzc3MjA2OTMxNDg2.YOWobw.vvj_Clb1bcWHig5ctCG0XwP0lfI"
channelID: "874609151966326804"