name: DiscordLink
version: ${project.version}
main: me.thecuddlybear.discordlink.DiscordLink
api-version: 1.17
authors: [ TheCuddlyBear ]
description: Link your minecraft chat with a discord channel
commands:
  dlink:
    description: Main command of the plugin.
